version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6800:6800"
    volumes:
      - ./editor-voz-document:/app/src:delegated
      - /app/node_modules
    environment:
      - VITE_API_URL=http://3.128.255.243
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

volumes:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge