version: '3.8'

services:
  backend:
    build:
      context: ./backen-michelle
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backen-michelle:/app/src/
    environment:
      - DB_HOST=db
      - DB_PORT=3302
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./editor-voz-document
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./editor-voz-document/src:/app/src
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - app-network

  db:
    image: mariadb:10.11
    command: --port=3302
    ports:
      - "3302:3302"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadb_data:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge 