version: '3.8'

services:
  backend:
    build:
      context: ./backen-michelle
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backen-michelle/src:/app/src
    environment:
      - PYTHONPATH=/app/src
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=editor_user
      - DB_PASSWORD=editor_password
      - DB_NAME=editor_voz_db
      - MYSQL_ROOT_PASSWORD=root_password
      - JWT_SECRET=your_super_secret_key
      - OPENAI_API_KEY=your_openai_key
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./editor-voz-document
      dockerfile: Dockerfile
    ports:
      - "6800:6800"
    volumes:
      - ./editor-voz-document:/app:delegated
      - /app/node_modules
    environment:
      - VITE_API_URL=http://3.128.255.243
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: editor_voz_db
      MYSQL_USER: editor_user
      MYSQL_PASSWORD: editor_password
      MYSQL_MAX_ALLOWED_PACKET: 128M
      MYSQL_WAIT_TIMEOUT: 28800
      MYSQL_INTERACTIVE_TIMEOUT: 28800
    command: >
      --max-allowed-packet=128M
      --wait-timeout=28800
      --interactive-timeout=28800
      --skip-name-resolve
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge 