version: '3.8'

services:
  backend:
    build:
      context: ./backen-michelle
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backen-michelle:/app/src/
    environment:
      - DATABASE_URL=mysql+pymysql://editor_user:editor_password@db:3302/editor_voz_db
      - DB_USER=editor_user
      - DB_PASSWORD=editor_password
      - DB_HOST=db
      - DB_PORT=3302
      - DB_NAME=editor_voz_db
      - MYSQL_ROOT_PASSWORD=root_password
      - JWT_SECRET=your_super_secret_key
      - OPENAI_API_KEY=your_openai_key
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./editor-voz-document
      dockerfile: Dockerfile
    ports:
      - "6800:6800"
    volumes:
      - ./editor-voz-document:/app:delegated
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  db:
    image: mariadb:10.11
    ports:
      - "3302:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=editor_voz_db
      - MYSQL_USER=editor_user
      - MYSQL_PASSWORD=editor_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge 